services:
  db:
    image: pgvector/pgvector:pg16
    container_name: rbi_db
    environment:
      POSTGRES_USER: rbi
      POSTGRES_PASSWORD: rbi_pass
      POSTGRES_DB: rbi_copilot
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
